// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFranchiseSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddFranchiseSource'](arg1, arg2, arg3, arg4);
}

export function BrowseLegacyDB() {
  return window['go']['main']['App']['BrowseLegacyDB']();
}

export function BrowseSaveFile() {
  return window['go']['main']['App']['BrowseSaveFile']();
}

export function ComputeSeasonStatLeaderAwards(arg1) {
  return window['go']['main']['App']['ComputeSeasonStatLeaderAwards'](arg1);
}

export function CreateCustomAward(arg1) {
  return window['go']['main']['App']['CreateCustomAward'](arg1);
}

export function CreateFranchise(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFranchise'](arg1, arg2, arg3, arg4);
}

export function DeleteFranchise(arg1) {
  return window['go']['main']['App']['DeleteFranchise'](arg1);
}

export function DetectLegacyDB() {
  return window['go']['main']['App']['DetectLegacyDB']();
}

export function GetActiveFranchise() {
  return window['go']['main']['App']['GetActiveFranchise']();
}

export function GetBattingCareerLeaders(arg1) {
  return window['go']['main']['App']['GetBattingCareerLeaders'](arg1);
}

export function GetBattingSeasonLeaders(arg1) {
  return window['go']['main']['App']['GetBattingSeasonLeaders'](arg1);
}

export function GetCareerLeaders() {
  return window['go']['main']['App']['GetCareerLeaders']();
}

export function GetHistoricalTeams(arg1, arg2) {
  return window['go']['main']['App']['GetHistoricalTeams'](arg1, arg2);
}

export function GetHoFCandidates() {
  return window['go']['main']['App']['GetHoFCandidates']();
}

export function GetHoFInducted() {
  return window['go']['main']['App']['GetHoFInducted']();
}

export function GetPitchingCareerLeaders(arg1) {
  return window['go']['main']['App']['GetPitchingCareerLeaders'](arg1);
}

export function GetPitchingSeasonLeaders(arg1) {
  return window['go']['main']['App']['GetPitchingSeasonLeaders'](arg1);
}

export function GetPlayerCareer(arg1) {
  return window['go']['main']['App']['GetPlayerCareer'](arg1);
}

export function GetPlayerCareerAwards(arg1) {
  return window['go']['main']['App']['GetPlayerCareerAwards'](arg1);
}

export function GetPlayerSeasonLog(arg1) {
  return window['go']['main']['App']['GetPlayerSeasonLog'](arg1);
}

export function GetSaveFileCandidates() {
  return window['go']['main']['App']['GetSaveFileCandidates']();
}

export function GetSeasonAwardCandidates(arg1) {
  return window['go']['main']['App']['GetSeasonAwardCandidates'](arg1);
}

export function GetSeasonChampionTeamHistoryID(arg1) {
  return window['go']['main']['App']['GetSeasonChampionTeamHistoryID'](arg1);
}

export function GetSeasonList() {
  return window['go']['main']['App']['GetSeasonList']();
}

export function GetSeasonPlayerAwards(arg1) {
  return window['go']['main']['App']['GetSeasonPlayerAwards'](arg1);
}

export function GetSeasonStatLeaders(arg1) {
  return window['go']['main']['App']['GetSeasonStatLeaders'](arg1);
}

export function GetStandings(arg1) {
  return window['go']['main']['App']['GetStandings'](arg1);
}

export function GetTeamHistory(arg1) {
  return window['go']['main']['App']['GetTeamHistory'](arg1);
}

export function GetTeamSeasonDetail(arg1) {
  return window['go']['main']['App']['GetTeamSeasonDetail'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListAllAwards() {
  return window['go']['main']['App']['ListAllAwards']();
}

export function ListAllTeamSeasons() {
  return window['go']['main']['App']['ListAllTeamSeasons']();
}

export function ListAwards(arg1) {
  return window['go']['main']['App']['ListAwards'](arg1);
}

export function ListFranchiseSources(arg1) {
  return window['go']['main']['App']['ListFranchiseSources'](arg1);
}

export function ListFranchises() {
  return window['go']['main']['App']['ListFranchises']();
}

export function ListLegacyFranchises(arg1) {
  return window['go']['main']['App']['ListLegacyFranchises'](arg1);
}

export function MigrateLegacyFranchise(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MigrateLegacyFranchise'](arg1, arg2, arg3, arg4);
}

export function OpenAppDataDir() {
  return window['go']['main']['App']['OpenAppDataDir']();
}

export function ProbeFranchiseSaveFile(arg1) {
  return window['go']['main']['App']['ProbeFranchiseSaveFile'](arg1);
}

export function ProbeLeagues(arg1) {
  return window['go']['main']['App']['ProbeLeagues'](arg1);
}

export function RenameFranchise(arg1, arg2) {
  return window['go']['main']['App']['RenameFranchise'](arg1, arg2);
}

export function ReplaceActiveFranchiseSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceActiveFranchiseSource'](arg1, arg2, arg3);
}

export function SearchPlayers(arg1) {
  return window['go']['main']['App']['SearchPlayers'](arg1);
}

export function SearchTeams(arg1) {
  return window['go']['main']['App']['SearchTeams'](arg1);
}

export function SelectFranchise(arg1) {
  return window['go']['main']['App']['SelectFranchise'](arg1);
}

export function SetHallOfFamer(arg1, arg2) {
  return window['go']['main']['App']['SetHallOfFamer'](arg1, arg2);
}

export function SetInitialSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetInitialSource'](arg1, arg2, arg3);
}

export function SetPlayerSeasonAwards(arg1) {
  return window['go']['main']['App']['SetPlayerSeasonAwards'](arg1);
}

export function SubmitSeasonAwards(arg1) {
  return window['go']['main']['App']['SubmitSeasonAwards'](arg1);
}

export function SyncSeason() {
  return window['go']['main']['App']['SyncSeason']();
}
