// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFranchise(arg1:string,arg2:string):Promise<main.FranchiseDTO>;

export function DeleteFranchise(arg1:string):Promise<void>;

export function GetActiveFranchise():Promise<main.FranchiseDTO>;

export function GetVersion():Promise<string>;

export function ListFranchises():Promise<Array<main.FranchiseDTO>>;

export function RenameFranchise(arg1:string,arg2:string):Promise<void>;

export function SelectFranchise(arg1:string):Promise<main.FranchiseDTO>;

export function SyncSeason(arg1:number,arg2:number):Promise<main.SyncSeasonResult>;
